//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntraTicket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Files = new HashSet<File>();
        }
    
        public int TicketID { get; set; }
        public int EmployeeIDFrom { get; set; }
        public int EmployeeIDAssignTo { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public string ResolutionMain { get; set; }
        public string Resolution1 { get; set; }
    
        public virtual Employee AssignedTo { get; set; }
        public virtual Employee FromUser { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual TicketCategory Category { get; set; }
    }
}
